server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: transport-system

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 路线规划配置
route:
  planner:
    # Python 模型服务地址
    model-service-url: http://localhost:5000
    # 拥堵系数权重
    congestion-alpha: 0.05
    # 最大连接距离（km）
    max-distance-km: 2.0
    # 数据文件路径
    node-data-file: classpath:data/sensors北交周边.csv
    edge-data-file: classpath:data/edges.csv

# 日志配置
logging:
  level:
    com.example.routeplanner: DEBUG
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"